[package]
name = "mini_blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
chrono = "0.4.22"
crypto-hash = "0.3.4"
serde = { version = "1.0.144", features = ["derive"] }
